"""
Rare-focused Stage 1 training.

Click-to-run. No argparse.
All paths are relative to root = Path.cwd().

Main rare-class improvements:
    - Rare-centered crops from preprocess.py are used automatically.
    - WeightedRandomSampler oversamples rare-class samples.
    - FN-focused Focal Tversky loss is blended in smoothly after warmup.
    - Class weights strongly emphasize rare tissue/nuclei classes.
    - Checkpoint selection is rare-focused through utils/metrics.py.
    - Best epoch is printed at the end.
    - SC-DFA and spatial prior are also ramped smoothly to avoid training shocks.
    - Checkpoints are safely saved via local /content then copied to Drive.
"""

import shutil
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import DataLoader, Subset, WeightedRandomSampler
try:
    import bitsandbytes as bnb
except Exception:
    bnb = None

from dataloaders import (
    INTERNAL_TISSUE_ID_TO_NAME,
    PUMA_NUCLEI_ID_TO_NAME,
    PUMADataset,
    get_train_transforms,
    get_val_transforms,
)
from models import UnifiedPanopticNet, get_cnn_spatial_prior
from train import train_one_epoch, validate
from utils import MultiTaskUncertaintyLoss, PUMAMetrics
from utils.split_utils import make_or_load_group_split


# ============================================================
# Click-to-run config
# ============================================================

root = Path.cwd()

data_dir = root / "dataset_processed"
uni_weight_dir = root
checkpoint_dir = root / "checkpoints"
split_file = checkpoint_dir / "split_seed42.npz"

image_size = 1024
stride = 768
batch_size = 12
epochs = 50
num_workers = 2
seed = 42
val_ratio = 0.2
force_new_split = False
val_original_only = True

lr = 1e-4
weight_decay = 1e-4

# Smooth schedule. Do not abruptly switch difficult losses/modules on.
focal_start_epoch = 10
focal_full_epoch = 16
focal_max_weight = 0.5

sc_dfa_start_epoch = 15
sc_dfa_full_epoch = 22
sc_dfa_max_weight = 0.3

prior_start_epoch = 20
prior_full_epoch = 28
prior_max_weight = 0.2

# Used only as fallback. PUMADataset reads site type from file name.
default_site_type = "metastatic"

# You said you have Cellpose and will use it. Keep this at 0.0 so training always
# uses the stored Cellpose flow files generated by preprocess.py.
zero_cellpose_prob = 0.0

# Oversample rare images more than once per epoch.
samples_per_epoch_multiplier = 1.0

multi_gpu = False
use_fp16 = True

# ---------------------------------------------------------
# CHANGED: Point resume to the last saved checkpoint
# ---------------------------------------------------------
resume = checkpoint_dir / "puma_epoch_last_s1.pth" 

# Class weights are repeated in checkpoint metadata for transparency.
tissue_class_weights = [1.0, 4.0, 0.8, 3.0, 7.0]
nuclei_class_weights = [0.8, 1.0, 7.0, 2.5, 4.5, 8.0, 2.0, 2.5, 5.5, 8.0]


def linear_ramp(epoch, start, end, max_value):
    """Return a smooth linear warmup value for epoch-level schedules."""
    if epoch < start:
        return 0.0
    if epoch >= end:
        return float(max_value)
    progress = (epoch - start + 1) / max(end - start + 1, 1)
    return float(max_value) * float(progress)


def apply_smooth_schedule(model, criterion, epoch):
    """Apply smooth Stage 1 schedule for rare semantic loss, SC-DFA, and prior."""
    core = model.module if hasattr(model, "module") else model

    focal_weight = linear_ramp(epoch, focal_start_epoch, focal_full_epoch, focal_max_weight)
    sc_dfa_weight = linear_ramp(epoch, sc_dfa_start_epoch, sc_dfa_full_epoch, sc_dfa_max_weight)
    prior_weight = linear_ramp(epoch, prior_start_epoch, prior_full_epoch, prior_max_weight)

    if hasattr(criterion, "set_focal_tversky_weight"):
        criterion.set_focal_tversky_weight(focal_weight)
    else:
        criterion.focal_tversky_weight = focal_weight

    if hasattr(core, "set_sc_dfa_lambda"):
        core.set_sc_dfa_lambda(sc_dfa_weight)
    elif hasattr(core, "enable_sc_dfa"):
        core.enable_sc_dfa(sc_dfa_weight > 0.0)

    if hasattr(core, "set_spatial_prior_lambda"):
        core.set_spatial_prior_lambda(prior_weight)

    print(
        f"[SmoothSchedule] epoch={epoch:03d} "
        f"focal={focal_weight:.3f} "
        f"sc_dfa={sc_dfa_weight:.3f} "
        f"prior={prior_weight:.3f}"
    )
    return focal_weight, sc_dfa_weight, prior_weight


def as_config_namespace():
    return SimpleNamespace(
        image_size=image_size,
        stride=stride,
        default_site_type=default_site_type,
    )


def safe_torch_save(obj, path):
    """Avoid Google Drive partial-write corruption for large checkpoints."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if Path("/content").exists():
        local_tmp = Path("/content") / (path.name + ".tmp")
        local_final = Path("/content") / path.name
    else:
        local_tmp = path.with_suffix(path.suffix + ".tmp")
        local_final = path

    torch.save(obj, local_tmp)
    _ = torch.load(local_tmp, map_location="cpu", weights_only=False)

    if local_final != local_tmp:
        local_tmp.replace(local_final)

    if local_final != path:
        shutil.copy2(local_final, path)
        _ = torch.load(path, map_location="cpu", weights_only=False)

    print(f"[Checkpoint] Saved and verified: {path}")


def make_inference_config(model):
    core = model.module if hasattr(model, "module") else model
    return {
        "architecture": "merged_v22_architecture_v4_labels_no_tissue_background_rare_focused",
        "image_size": image_size,
        "tile_size": image_size,
        "stride": stride,
        "num_tissue_classes": 5,
        "num_nuclei_classes": 10,
        "use_sc_dfa": bool(core.use_sc_dfa),
        "lambda_sc_dfa": float(getattr(core, "lambda_sc_dfa", 0.0)),
        "lambda_prior": float(core.lambda_prior),
        "default_site_type": default_site_type,
        "internal_tissue_id_to_name": INTERNAL_TISSUE_ID_TO_NAME,
        "puma_nuclei_id_to_name": PUMA_NUCLEI_ID_TO_NAME,
        "tissue_internal_to_puma_rule": "puma_id = internal_id + 1; no model background channel",
        "normalization_mean": [0.485, 0.456, 0.406],
        "normalization_std": [0.229, 0.224, 0.225],
        "cellpose_mode_at_training": "real_cellpose_flows_from_dataset_processed_cellpose_flows",
        "zero_cellpose_prob": zero_cellpose_prob,
        "rare_focused_training": True,
        "batch_size": batch_size,
        "epochs": epochs,
        "tissue_class_weights": tissue_class_weights,
        "nuclei_class_weights": nuclei_class_weights,
        "samples_per_epoch_multiplier": samples_per_epoch_multiplier,
        "max_sample_weight": 15.0,
        "smooth_stage1_schedule": {
            "focal_start_epoch": focal_start_epoch,
            "focal_full_epoch": focal_full_epoch,
            "focal_max_weight": focal_max_weight,
            "sc_dfa_start_epoch": sc_dfa_start_epoch,
            "sc_dfa_full_epoch": sc_dfa_full_epoch,
            "sc_dfa_max_weight": sc_dfa_max_weight,
            "prior_start_epoch": prior_start_epoch,
            "prior_full_epoch": prior_full_epoch,
            "prior_max_weight": prior_max_weight,
        },
        "stage1_checkpoint_name": "puma_epoch_best_s1.pth",
        "stage2_checkpoint_name": "nuclei_refiner_residual_best.pth",
        "split_is_group_based": True,
        "validation_original_only": val_original_only,
    }


def save_checkpoint(path, model, criterion, optimizer, scheduler, scaler, epoch, best_score, val_report):
    core = model.module if hasattr(model, "module") else model
    payload = {
        "epoch": int(epoch),
        "model_state": core.state_dict(),
        "criterion_state": criterion.state_dict(),
        "optimizer_state": optimizer.state_dict() if optimizer is not None else None,
        "scheduler_state": scheduler.state_dict() if scheduler is not None else None,
        "scaler_state": scaler.state_dict() if scaler is not None else None,
        "best_score": float(best_score),
        "best_val_report": val_report,
        "inference_config": make_inference_config(core),
    }
    safe_torch_save(payload, path)


def make_rare_weighted_sampler(dataset, indices):
    weights = np.asarray(dataset.compute_sample_weights(indices), dtype=np.float64)
    #weights = np.clip(weights, 1.0, 40.0)
    weights = np.clip(weights, 1.0, 15.0)
    num_samples = int(round(len(indices) * samples_per_epoch_multiplier))
    num_samples = max(num_samples, len(indices))
    print(
        f"[Sampler] rare weighted sampler: n_indices={len(indices)} "
        f"num_samples={num_samples} min_w={weights.min():.2f} "
        f"mean_w={weights.mean():.2f} max_w={weights.max():.2f}"
    )
    return WeightedRandomSampler(
        weights=torch.as_tensor(weights, dtype=torch.double),
        num_samples=num_samples,
        replacement=True,
    )


def print_report(epoch, train_loss, val):
    tissue_names = [INTERNAL_TISSUE_ID_TO_NAME[i] for i in range(5)]
    nuclei_names = [PUMA_NUCLEI_ID_TO_NAME[i] for i in range(10)]
    print("\n" + "=" * 88)
    print(
        f"Epoch {epoch:03d} | train_loss={train_loss:.4f} | "
        f"val_loss={val.get('val_loss', 0):.4f} | selection={val.get('selection_score', 0):.4f} | "
        f"rare={val.get('rare_macro_dice', 0):.4f}"
    )
    print("-" * 88)
    print(f"Tissue loss={val.get('loss_tissue', 0):.4f}")
    for i, name in enumerate(tissue_names):
        print(f"  {i}: {name:<22} dice={val.get(f'tissue_dice_{i}', 0):.4f} iou={val.get(f'tissue_iou_{i}', 0):.4f}")
    print(f"Nuclei loss={val.get('loss_nc', 0):.4f}")
    for i, name in enumerate(nuclei_names):
        print(f"  {i}: {name:<22} dice={val.get(f'nuclei_dice_{i}', 0):.4f} iou={val.get(f'nuclei_iou_{i}', 0):.4f}")
    print(f"NP loss={val.get('loss_np', 0):.4f} | HV loss={val.get('loss_hv', 0):.4f}")
    print(
        f"avg_tissue={val.get('avg_tissue_dice', 0):.4f} | "
        f"avg_nuclei={val.get('avg_nuclei_dice', 0):.4f} | "
        f"rare_tissue={val.get('rare_tissue_macro_dice', 0):.4f} | "
        f"rare_nuclei={val.get('rare_nuclei_macro_dice', 0):.4f}"
    )
    print("=" * 88 + "\n")


def main():
    torch.manual_seed(seed)
    np.random.seed(seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.backends.cudnn.benchmark = True
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    print(f"[Root] {root}")
    print(f"[Data] {data_dir}")
    print(f"[Checkpoints] {checkpoint_dir}")
    print(f"[Config] batch_size={batch_size} epochs={epochs} zero_cellpose_prob={zero_cellpose_prob}")

    train_ds = PUMADataset(
        data_dir,
        transforms=get_train_transforms(image_size),
        zero_cellpose_prob=zero_cellpose_prob,
    )
    val_ds = PUMADataset(
        data_dir,
        transforms=get_val_transforms(image_size),
        zero_cellpose_prob=0.0,
    )

    split_meta = train_ds.get_split_metadata()
    train_idx, val_idx = make_or_load_group_split(
        source_names=split_meta["source_names"],
        is_original=split_meta["is_original"],
        split_path=split_file,
        seed=seed,
        train_fraction=1.0 - val_ratio,
        force_new=force_new_split,
        val_original_only=val_original_only,
    )
    print(f"[Split] train={len(train_idx)} val={len(val_idx)} file={split_file}")
    print("[Split] Leakage-safe: all rare crops stay with their source image; validation uses originals only.")

    train_loader = DataLoader(
        Subset(train_ds, train_idx),
        batch_size=batch_size,
        sampler=make_rare_weighted_sampler(train_ds, train_idx),
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False,
    )
    val_loader = DataLoader(
        Subset(val_ds, val_idx),
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False,
    )

    cnn = get_cnn_spatial_prior(pretrained=True)
    model = UnifiedPanopticNet(
        vit_model=uni_weight_dir,
        cnn_model=cnn,
        num_tissue=5,
        num_nuclei=10,
        load_uni_weights=True,
    ).to(device)

    if multi_gpu and torch.cuda.device_count() > 1:
        model = torch.nn.DataParallel(model)

    criterion = MultiTaskUncertaintyLoss(
        tissue_weights=torch.tensor(tissue_class_weights, dtype=torch.float32),
        nuclei_weights=torch.tensor(nuclei_class_weights, dtype=torch.float32),
    ).to(device)
    params = list(model.parameters()) + list(criterion.parameters())

    if bnb is not None and device.type == "cuda":
        try:
            optimizer = bnb.optim.AdamW8bit(params, lr=lr, weight_decay=weight_decay)
        except Exception:
            optimizer = optim.AdamW(params, lr=lr, weight_decay=weight_decay)
    else:
        optimizer = optim.AdamW(params, lr=lr, weight_decay=weight_decay)

    total_steps = epochs * max(len(train_loader), 1)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=total_steps)
    scaler = torch.amp.GradScaler("cuda", enabled=device.type == "cuda" and use_fp16)
    metrics = PUMAMetrics()

    # ---------------------------------------------------------
    # CHANGED: Full state-resume logic applied here
    # ---------------------------------------------------------
    best_score = -1.0
    best_epoch = 0
    best_val_report = None
    start_epoch = 1

    if resume is not None:
        resume_path = Path(resume)
        if resume_path.is_file():
            print(f"[INFO] Resuming from checkpoint: {resume_path}")
            checkpoint = torch.load(resume_path, map_location=device, weights_only=False)
            
            # Load model state
            core = model.module if hasattr(model, "module") else model
            core.load_state_dict(checkpoint["model_state"])
            
            # Load criterion state (loss function variables)
            if "criterion_state" in checkpoint and checkpoint["criterion_state"] is not None:
                criterion.load_state_dict(checkpoint["criterion_state"], strict=False)
                
            # Load optimizer state (momentum, gradients context)
            if "optimizer_state" in checkpoint and checkpoint["optimizer_state"] is not None:
                optimizer.load_state_dict(checkpoint["optimizer_state"])
                
            # Load scheduler state (current LR step)
            if "scheduler_state" in checkpoint and checkpoint["scheduler_state"] is not None:
                scheduler.load_state_dict(checkpoint["scheduler_state"])
                
            # Load scaler state (for mixed precision stability)
            if "scaler_state" in checkpoint and checkpoint["scaler_state"] is not None:
                scaler.load_state_dict(checkpoint["scaler_state"])
                
            # Load epoch tracking
            start_epoch = checkpoint["epoch"] + 1
            best_score = checkpoint.get("best_score", -1.0)
            best_val_report = checkpoint.get("best_val_report", None)
            
            print(f"[INFO] Resumed successfully. Starting from epoch {start_epoch}, current best score: {best_score:.4f}")
        else:
            print(f"[WARN] Resume path {resume_path} does not exist. Starting from scratch.")

    # ---------------------------------------------------------
    # CHANGED: Range now starts precisely at 'start_epoch'
    # ---------------------------------------------------------
    for epoch in range(start_epoch, epochs + 1):
        core = model.module if hasattr(model, "module") else model

        apply_smooth_schedule(model, criterion, epoch)

        train_loss = train_one_epoch(
            model,
            train_loader,
            optimizer,
            criterion,
            scheduler,
            device,
            scaler,
            epoch,
        )
        val = validate(model, val_loader, criterion, metrics, device, epoch)
        print_report(epoch, train_loss, val)

        score = float(val.get("selection_score", -val.get("val_loss", 1e9)))
        if score > best_score:
            best_score = score
            best_epoch = epoch
            best_val_report = dict(val)
            save_path = checkpoint_dir / "puma_epoch_best_s1.pth"
            save_checkpoint(save_path, model, criterion, optimizer, scheduler, scaler, epoch, best_score, best_val_report)
            print(f"Saved best full checkpoint: {save_path} | epoch={best_epoch} score={best_score:.4f}")

        # ---------------------------------------------------------
        # CHANGED: Save verified last checkpoint EVERY epoch so
        # you won't lose progression. The global best_score/report
        # is also passed so it survives the resume process correctly.
        # ---------------------------------------------------------
        last_path = checkpoint_dir / "puma_epoch_last_s1.pth"
        save_checkpoint(last_path, model, criterion, optimizer, scheduler, scaler, epoch, best_score, best_val_report)

    print("\n" + "=" * 88)
    print(f"Stage 1 complete. Best epoch used as checkpoint: {best_epoch}")
    print(f"Best selection score: {best_score:.4f}")
    if best_val_report is not None:
        print(f"Best rare macro dice: {best_val_report.get('rare_macro_dice', 0):.4f}")
        print(f"Best rare tissue dice: {best_val_report.get('rare_tissue_macro_dice', 0):.4f}")
        print(f"Best rare nuclei dice: {best_val_report.get('rare_nuclei_macro_dice', 0):.4f}")
    print(f"Best checkpoint: {checkpoint_dir / 'puma_epoch_best_s1.pth'}")
    print("=" * 88)


if __name__ == "__main__":
    main()